### PR TITLE
Add the mod icon and improve the name-description of the mod

### PR DESCRIPTION
**Pull request by RaptaG**
`+` improve the README

### CODE REVIEW

**Comment by r0yzer** [comment]
thanks for your contribution, i appreciate it. however i would not like to merge your pr, i have still to decide on a final logo which is a little bit better than just a simple minecraft screenshot. and i dont really get why you changed the mod description, i thought it fits pretty good

**Comment by RaptaG** [comment]
> I have still to decide on a final logo which is a little bit better than just a simple minecraft screenshot.

👍, let me know when you decide the final logo

 
> I don't really get why you changed the mod description, I thought it fits pretty good

I can put it back to the original if you want to

**Comment by r0yzer** [comment]
yeah, if you have some idea for a logo let me know

**Comment by r0yzer** [comment]
maybe, let me ask @jakobkmar if he has an idea

**Comment by RaptaG** [comment]
Cool

**Comment by RaptaG** [comment]
What's going on with this?

**Comment by FlerBuster** [comment]
r0yzer is mal wieder sleeping

**Comment by FlerBuster** [comment]
soll passieren sometimes

**Comment by RaptaG** [comment]
This is dead, I'm closing it.

**Pull request closed without merging**
