### PR TITLE
add SettingsGui.kt

### PR DESCRIPTION
**Pull request by FlerBuster**

### CODE REVIEW

**Comment by FlerBuster** [comment]
hm i dint even say it was finished

**Comment by FlerBuster** [comment]
okey then halt nicht

**Comment by FlerBuster** [comment]
arsch

**Comment by r0yzer** [comment]
please do not contact me anymore

**Comment by FlerBuster** [comment]
wrong gehofft

**Comment by r0yzer** [comment]
19. Olexesh - Authentic Athletic - HIGH

**Pull request closed without merging**
